// Input JSON array
const jsonData =
  [

    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MECH-MX-X2G2-REAR-LP",
      "NameParent": "MECH Part MX X2G2 Rear with Light Pipes",
      "Position": 1,
      "SKChild": 100,
      "RegNumberChild": "MECH-MX-X2G2-REAR",
      "NameChild": "MECH Part MX X2G2 Rear",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 4.0177
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MECH-MX-X2G2-REAR-LP",
      "NameParent": "MECH Part MX X2G2 Rear with Light Pipes",
      "Position": 2,
      "SKChild": 100,
      "RegNumberChild": "MECH-LIGHTPIPE-1.63X4.14",
      "NameChild": "LIGHTPIPE DIA 1.63MM LENGTH 4.14MM",
      "MNF": 4,
      "MJ": "pcs",
      "TotalPrice": 0.920484
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MECH-O-RING-22X1-VI370-CL",
      "NameParent": "Filter glass O-Ring, 22x1mm, FKM, Vi370, black, cleaned",
      "Position": 1,
      "SKChild": 100,
      "RegNumberChild": "MECH-O-RING-22X1-VI370",
      "NameChild": "Filter glass O-Ring, 22x1mm, FKM, Vi370, black",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.109396
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 1,
      "SKChild": 100,
      "RegNumberChild": "FLT-BK7-AR2X-D25",
      "NameChild": "25mm dia BK7 ARx2",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 3.284358
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 2,
      "SKChild": 100,
      "RegNumberChild": "MECH-MT-MID-023",
      "NameChild": "MECH MT023 Middle Part",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 4.709304
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 3,
      "SKChild": 300,
      "RegNumberChild": "MT023MG-PR-SENSOR-PCA",
      "NameChild": "MT IMX174LLJ-C Sensor Board PCA",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 4,
      "SKChild": 100,
      "RegNumberChild": "SROB-M1.6X3-SLOT-STNLS",
      "NameChild": "DIN 84 M1.6x3 Slot Cheese, Stainless, Screw",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.140212
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 5,
      "SKChild": 100,
      "RegNumberChild": "MECH-MQ-FRONT",
      "NameChild": "MECH Part MQ Front",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 3.299751
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 6,
      "SKChild": 100,
      "RegNumberChild": "MECH-MQ-CS-C",
      "NameChild": "MECH Part MQ Middle, extending focal distance from CS to C mount",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 2.2978
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 7,
      "SKChild": 100,
      "RegNumberChild": "SROB-M2X14-CUST",
      "NameChild": "M2x14, custom low profile screw, black",
      "MNF": 4,
      "MJ": "pcs",
      "TotalPrice": 0.034804
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 8,
      "SKChild": 100,
      "RegNumberChild": "MECH-MT023XG-SY-GSKT",
      "NameChild": "MECH MT023xG-SY sensor front antidust gasket",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.59785
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 9,
      "SKChild": 300,
      "RegNumberChild": "MECH-O-RING-22X1-VI370-CL",
      "NameChild": "Filter glass O-Ring, 22x1mm, FKM, Vi370, black, cleaned",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-FRONT-SUBASSM",
      "NameParent": "MT IMX174LLJ-C B/W Front Subassembly",
      "Position": 10,
      "SKChild": 100,
      "RegNumberChild": "MECH-C-MOUNT-CAP",
      "NameChild": "Plastic C-Mount Protective Cap",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.700685
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 1,
      "SKChild": 100,
      "RegNumberChild": "C-0402-4U7-6.3V-X5R",
      "NameChild": "CAP CER 4.7uF 6.3V 20% X5R 0402 H<=0.50MM",
      "MNF": 6,
      "MJ": "pcs",
      "TotalPrice": 0.019668
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 2,
      "SKChild": 100,
      "RegNumberChild": "C-0402-U10-25V-X5R",
      "NameChild": "CAP CER .1UF 25V X5R 0402 H<=0.55MM",
      "MNF": 31,
      "MJ": "pcs",
      "TotalPrice": 0.039556
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 3,
      "SKChild": 100,
      "RegNumberChild": "C-0402-U22-25V-X5R",
      "NameChild": "CAP CER 0.22UF 25V 20% X5R 0402",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.01331
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 4,
      "SKChild": 100,
      "RegNumberChild": "C-0603-10U-6V3-LOW",
      "NameChild": "CAP CER 10UF 6.3V X5R 20% 0603 H<=0.50MM",
      "MNF": 43,
      "MJ": "pcs",
      "TotalPrice": 1.69076
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 5,
      "SKChild": 100,
      "RegNumberChild": "CONN-DF40HC(2.5)-60DS",
      "NameChild": "CONN RCPT 60POS 0.4MM SMD GOLD",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.984302
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 6,
      "SKChild": 100,
      "RegNumberChild": "DS2411R",
      "NameChild": "IC Serial Number Registration Silicon Serial Number 1.8V SOT-23",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.779841
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 7,
      "SKChild": 100,
      "RegNumberChild": "IMX174LLJ-C",
      "NameChild": "CMOS 2.35Mpix, 1/1.2, B/W, GS",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 123.95
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 8,
      "SKChild": 100,
      "RegNumberChild": "L-0603-120R-3A",
      "NameChild": "FERRITE CHIP 120 OHMS 3.0A 0603",
      "MNF": 6,
      "MJ": "pcs",
      "TotalPrice": 0.172158
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 9,
      "SKChild": 100,
      "RegNumberChild": "LT1965EDD-3.3#PBF",
      "NameChild": "IC REG LDO 3.3V 1.1A 8-DFN",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 2.088703
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 10,
      "SKChild": 100,
      "RegNumberChild": "PCB-MT-PR-SENSOR",
      "NameChild": "Bare PCB",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 2.821405
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 11,
      "SKChild": 100,
      "RegNumberChild": "R-0402-4K99-1P",
      "NameChild": "RES 4.99K OHM 1/16W 1% 0402 SMD",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.003816
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 12,
      "SKChild": 100,
      "RegNumberChild": "R-0402-10K-1P",
      "NameChild": "RES 10.0K OHM 1/16W 1% 0402 SMD",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.007196
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 13,
      "SKChild": 100,
      "RegNumberChild": "R-0402-10R-1P",
      "NameChild": "RES 10.0 OHM 1/16W 1% 0402 SMD",
      "MNF": 12,
      "MJ": "pcs",
      "TotalPrice": 0.032184
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 14,
      "SKChild": 100,
      "RegNumberChild": "TMP112",
      "NameChild": "IC TEMP SENSOR DGTL 5V SOT563",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.672325
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MT023MG-PR-SENSOR-PCA",
      "NameParent": "MT IMX174LLJ-C Sensor Board PCA",
      "Position": 15,
      "SKChild": 100,
      "RegNumberChild": "R-0402-1K0-1P",
      "NameChild": "RES 1.00K OHM 1/16W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.003686
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 1,
      "SKChild": 100,
      "RegNumberChild": "C-0402-2U2-6V3",
      "NameChild": "CAP CER 2.2UF 6.3V X5R 0402 H<=0.55MM",
      "MNF": 24,
      "MJ": "pcs",
      "TotalPrice": 0.0588
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 2,
      "SKChild": 100,
      "RegNumberChild": "C-0603-22U-16V-X5R-H080",
      "NameChild": "CAP CER 22uF 16V X5R 0603 H<=0.80MM",
      "MNF": 15,
      "MJ": "pcs",
      "TotalPrice": 1.56
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 3,
      "SKChild": 100,
      "RegNumberChild": "C-0402-U10-25V-X5R",
      "NameChild": "CAP CER .1UF 25V X5R 0402 H<=0.55MM",
      "MNF": 9,
      "MJ": "pcs",
      "TotalPrice": 0.011484
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 4,
      "SKChild": 100,
      "RegNumberChild": "C-0402-1N-50V",
      "NameChild": "CAP CER 1nF 50V 10% X7R 0402 H<=0.55MM",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.006394
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 5,
      "SKChild": 100,
      "RegNumberChild": "C-0603-4U7-35V-X5R",
      "NameChild": "CAP CER 4.7UF 35V 10% X5R 0603 H<=1.00MM",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.046868
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 6,
      "SKChild": 100,
      "RegNumberChild": "C-1206-22U-35V-X5R",
      "NameChild": "CAP CER 22UF 35V X5R 1206 H<=1.8MM",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.143472
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 7,
      "SKChild": 100,
      "RegNumberChild": "C-0402-10P-50V",
      "NameChild": "CAP CER 10PF 50V 5% C0G 0402 H<=0.55MM",
      "MNF": 4,
      "MJ": "pcs",
      "TotalPrice": 0.012248
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 8,
      "SKChild": 100,
      "RegNumberChild": "LED-0402-RED",
      "NameChild": "LED RED/CLEAR 636NM 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.116201
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 9,
      "SKChild": 100,
      "RegNumberChild": "LED-0402-GRN",
      "NameChild": "LED GRN/CLEAR 574NM 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.077968
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 10,
      "SKChild": 100,
      "RegNumberChild": "LED-0402-BLUE",
      "NameChild": "LED BLUE/CLEAR 470NM 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.07721
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 11,
      "SKChild": 100,
      "RegNumberChild": "LED-0402-AMBER",
      "NameChild": "LED AMBER/CLEAR 590NM 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.053593
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 12,
      "SKChild": 100,
      "RegNumberChild": "D-BAS40LP-7",
      "NameChild": "DIODE SCHOTTKY 40V DFN1006-2",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.085174
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 13,
      "SKChild": 100,
      "RegNumberChild": "BZX884-B2V7",
      "NameChild": "DIODE ZENER 250MW 2.7V SOD882",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.057578
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 14,
      "SKChild": 100,
      "RegNumberChild": "PTC-0603-0.036A-24V",
      "NameChild": "Resetable PTC Fuse 36mA 24V SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.084363
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 15,
      "SKChild": 100,
      "RegNumberChild": "CONN-502244-2430",
      "NameChild": "CONN FPC/FFC ZIF 24POS 0.5MM HORIZ BOTTOM CONTACT SMT",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.889418
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 16,
      "SKChild": 100,
      "RegNumberChild": "CONN-DF40C-60DP-0.4V(51)",
      "NameChild": "CONN RCPT 60POS 0.4MM SMD GOLD",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.786434
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 17,
      "SKChild": 100,
      "RegNumberChild": "CONN-DF40C-20DS-0.4V(51)",
      "NameChild": "CONN RCPT 20POS 0.4MM SMD GOLD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.223696
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 18,
      "SKChild": 100,
      "RegNumberChild": "L-0603-220R-2A",
      "NameChild": "FERRITE CHIP 220 OHMS 2.0A 0603",
      "MNF": 4,
      "MJ": "pcs",
      "TotalPrice": 0.076572
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 19,
      "SKChild": 100,
      "RegNumberChild": "L-XFL3012-102ME",
      "NameChild": "Coilcraft, 1uH, 2.6A, XFL3012 Series Shielded Power Inductors",
      "MNF": 3,
      "MJ": "pcs",
      "TotalPrice": 1.224462
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 20,
      "SKChild": 100,
      "RegNumberChild": "L-0603-1U0-DFE18SAN1R0MG0",
      "NameChild": "INDUCTOR SHIELDED POWER 1.0UH 1.7A 20% 0603 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.142895
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 21,
      "SKChild": 100,
      "RegNumberChild": "L-0402-BLM15PX121SN1D",
      "NameChild": "Inductor Ferrite Bead 120R/100MHz 2A 0402",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.01552
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 22,
      "SKChild": 100,
      "RegNumberChild": "R-0402-560K-1P",
      "NameChild": "RES 560K OHM 1/10W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.004916
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 23,
      "SKChild": 100,
      "RegNumberChild": "R-0402-140K-1P",
      "NameChild": "RES 140K OHM 1/16W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.000854
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 24,
      "SKChild": 100,
      "RegNumberChild": "R-0402-33K-1P",
      "NameChild": "RES 33.0K OHM 1/10W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.00376
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 25,
      "SKChild": 100,
      "RegNumberChild": "R-0402-100K-1P",
      "NameChild": "RES 100K OHM 1/16W 1% 0402 SMD",
      "MNF": 7,
      "MJ": "pcs",
      "TotalPrice": 0.026523
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 26,
      "SKChild": 100,
      "RegNumberChild": "R-0402-60K4-1P",
      "NameChild": "RES 60.4K OHM 1/16W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.001559
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 27,
      "SKChild": 100,
      "RegNumberChild": "R-0402-261K-1P",
      "NameChild": "RES 261.0K OHM 1/10W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.003168
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 28,
      "SKChild": 100,
      "RegNumberChild": "R-0402-100R-1P",
      "NameChild": "RES 100 OHM 1/16W 1% 0402 SMD",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.007776
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 29,
      "SKChild": 100,
      "RegNumberChild": "R-0402-10K-1P",
      "NameChild": "RES 10.0K OHM 1/16W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.003598
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 30,
      "SKChild": 100,
      "RegNumberChild": "R-0402-150R-1P",
      "NameChild": "RES 150 OHM 1/16W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.002888
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 31,
      "SKChild": 100,
      "RegNumberChild": "R-0402-1K0-1P",
      "NameChild": "RES 1.00K OHM 1/16W 1% 0402 SMD",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.007372
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 32,
      "SKChild": 100,
      "RegNumberChild": "R-0402-4K99-1P",
      "NameChild": "RES 4.99K OHM 1/16W 1% 0402 SMD",
      "MNF": 7,
      "MJ": "pcs",
      "TotalPrice": 0.013356
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 33,
      "SKChild": 100,
      "RegNumberChild": "R-0402-0R0-1P",
      "NameChild": "RES 0.0 OHM 1/10W 0402 SMD",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.005
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 34,
      "SKChild": 100,
      "RegNumberChild": "R-0402-620R-1P",
      "NameChild": "RES 620 OHM 1/16W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.002677
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 35,
      "SKChild": 100,
      "RegNumberChild": "R-0402-240R-1P",
      "NameChild": "RES 240 OHM 1/10W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.001584
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 36,
      "SKChild": 100,
      "RegNumberChild": "R-0402-49K9-1P",
      "NameChild": "RES 49.9K OHM 1/16W 1% 0402 SMD",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.004503
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 37,
      "SKChild": 100,
      "RegNumberChild": "R-0402-330R-1P",
      "NameChild": "RES 330 OHM 1/16W 1% 0402 SMD",
      "MNF": 5,
      "MJ": "pcs",
      "TotalPrice": 0.02923
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 38,
      "SKChild": 100,
      "RegNumberChild": "RP-4X0201-4K7-5P",
      "NameChild": "RES ARRAY 4.7K OHM 4 RES 0502",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.084144
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 39,
      "SKChild": 100,
      "RegNumberChild": "T-BC847CDLP",
      "NameChild": "TRANS DUAL NPN 45V 100mA SMD DFN1310-6",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.065747
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 40,
      "SKChild": 100,
      "RegNumberChild": "BJT-NPN-300V-SOT323",
      "NameChild": "TRANSISTOR NPN 300V 200MA SOT323",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.026584
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 41,
      "SKChild": 100,
      "RegNumberChild": "LTC3315AIV",
      "NameChild": "IC Synchronous Dual Step-Down DC-DC Converter, ADJ 2A LQFN-12",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 6.241272
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 42,
      "SKChild": 100,
      "RegNumberChild": "XC7A50T-2CPG236C",
      "NameChild": "IC FPGA Artix 7, 52160 cells, 106 I/O, CSBGA236",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 35.373238
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 43,
      "SKChild": 100,
      "RegNumberChild": "TPS3895ADRYR",
      "NameChild": "IC ADJ SUPERVISOR SON-6",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.368346
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 44,
      "SKChild": 100,
      "RegNumberChild": "TPD4E004DRYR",
      "NameChild": "IC ESD-PROT ARRAY 4CH 6-SON",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.127014
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 45,
      "SKChild": 100,
      "RegNumberChild": "EMIF04-1K030F3",
      "NameChild": "RC PI EMI Filter 1K/24pF WFBGA-9",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.382235
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 46,
      "SKChild": 100,
      "RegNumberChild": "FODM8801B",
      "NameChild": "Transistor Output Optocouplers OptoHiT Phototrans 75V 1-Ch CTR 260%",
      "MNF": 2,
      "MJ": "pcs",
      "TotalPrice": 0.77637
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 47,
      "SKChild": 100,
      "RegNumberChild": "TPS79925YZU",
      "NameChild": "IC LDO REG 200MA 2.5V 5-DSBGA",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.210558
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 48,
      "SKChild": 100,
      "RegNumberChild": "S25FL128SAGBHI200",
      "NameChild": "IC FLASH 128MBIT 133MHz BGA24",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 2.552054
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 49,
      "SKChild": 100,
      "RegNumberChild": "LTM8065",
      "NameChild": "IC REG DC-DC 2.5A 40V ADJ",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 11.629422
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-MAIN-FL-PCA",
      "NameParent": "MX Main board X2G2 PCIe, Horizontal",
      "Position": 50,
      "SKChild": 100,
      "RegNumberChild": "PCB-MX-X2G2-MAIN",
      "NameChild": "Bare PCB",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 3.143757
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-REAR-FL-SUBASSM",
      "NameParent": "MX X2G2 Rear Subassembly, Horizontal",
      "Position": 1,
      "SKChild": 300,
      "RegNumberChild": "MX-X2G2-MAIN-FL-PCA",
      "NameChild": "MX Main board X2G2 PCIe, Horizontal",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-REAR-FL-SUBASSM",
      "NameParent": "MX X2G2 Rear Subassembly, Horizontal",
      "Position": 2,
      "SKChild": 300,
      "RegNumberChild": "MECH-MX-X2G2-REAR-LP",
      "NameChild": "MECH Part MX X2G2 Rear with Light Pipes",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0
    },
    {
      "AltKV": 0,
      "SKParent": 300,
      "RegNumberParent": "MX-X2G2-REAR-FL-SUBASSM",
      "NameParent": "MX X2G2 Rear Subassembly, Horizontal",
      "Position": 3,
      "SKChild": 100,
      "RegNumberChild": "TP-10X10X1-TGA6200",
      "NameChild": "Thermal pad 10x10x1.0mm, TG-A6200, 6.2W/m-K",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0.103214
    },
    {
      "AltKV": 0,
      "SKParent": 401,
      "RegNumberParent": "MX023MG-SY-X2G2-FL",
      "NameParent": "MX IMX174LLJ-C B/W PCIe X2G2 Camera, Horizontal",
      "Position": 1,
      "SKChild": 300,
      "RegNumberChild": "MX-X2G2-REAR-FL-SUBASSM",
      "NameChild": "MX X2G2 Rear Subassembly, Horizontal",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0
    },
    {
      "AltKV": 0,
      "SKParent": 401,
      "RegNumberParent": "MX023MG-SY-X2G2-FL",
      "NameParent": "MX IMX174LLJ-C B/W PCIe X2G2 Camera, Horizontal",
      "Position": 2,
      "SKChild": 300,
      "RegNumberChild": "MT023MG-FRONT-SUBASSM",
      "NameChild": "MT IMX174LLJ-C B/W Front Subassembly",
      "MNF": 1,
      "MJ": "pcs",
      "TotalPrice": 0
    },
    {
      "AltKV": 0,
      "SKParent": 401,
      "RegNumberParent": "MX023MG-SY-X2G2-FL",
      "NameParent": "MX IMX174LLJ-C B/W PCIe X2G2 Camera, Horizontal",
      "Position": 3,
      "SKChild": 100,
      "RegNumberChild": "SROB-M2X10-CUST",
      "NameChild": "M2x10, custom low profile screw, black",
      "MNF": 4,
      "MJ": "pcs",
      "TotalPrice": 0.031656
    }
   

  ];

// Transformation logic
const Structure = Object.values(
  jsonData.reduce((acc, row) => {
    const parentKey = row.RegNumberParent; // Group by RegNumberParent
    if (!acc[parentKey]) {
      acc[parentKey] = {
        AltKV: row.AltKV,
        SKParent: row.SKParent,
        RegNumberParent: row.RegNumberParent,
        NameParent: row.NameParent,
        Position: row.Position,
        Parts: []
      };
    }
    acc[parentKey].Parts.push({
      SKChild: row.SKChild,
      RegNumberChild: row.RegNumberChild,
      NameChild: row.NameChild,
      MNF: row.MNF,
      MJ: row.MJ,
      TotalPrice: row.TotalPrice
    });
    return acc;
  }, {})
);

const outputData = {
  "Name": "MX023MG-SY-X2G2-FL",
  Structure
};

console.log(JSON.stringify(outputData, null, 2));